INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('Wireless Headphones', 'High-quality noise-canceling headphones with 30-hour battery life.', 199.99, 150);
INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('Bluetooth Speaker', 'Portable waterproof speaker with 12-hour playtime.', 69.95, 200);
INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('Smart Watch', 'Fitness tracker with heart rate monitor and GPS.', 149.99, 120);
INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('4K Webcam', 'Ultra HD webcam with adjustable stand and microphone.', 89.99, 80);
INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('E-Book Reader', 'E-ink display with 8GB storage and built-in light.', 129.50, 100);
INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('Gaming Mouse', 'RGB customizable gaming mouse with 16,000 DPI.', 49.99, 180);
INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('Wireless Charger', 'Fast Qi-certified wireless charging pad.', 29.95, 250);
INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('Noise-Canceling Earbuds', 'Compact earbuds with 24-hour battery life.', 129.99, 140);
INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('Tablet', '10-inch tablet with stylus and 64GB storage.', 249.99, 90);
INSERT INTO public.products (name, description, price, stock_quantity) VALUES ('Desk Lamp', 'Adjustable LED desk lamp with 5 brightness levels.', 39.99, 200);
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('John', 'Doe', 'john.doe@example.com', 'hashed_password_1');
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('Jane', 'Smith', 'jane.smith@example.com', 'hashed_password_2');
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('Michael', 'Johnson', 'michael.j@example.com', 'hashed_password_3');
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('Emily', 'Williams', 'emily.williams@example.com', 'hashed_password_4');
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('David', 'Brown', 'david.brown@example.com', 'hashed_password_5');
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('Sarah', 'Miller', 'sarah.miller@example.com', 'hashed_password_6');
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('James', 'Taylor', 'james.taylor@example.com', 'hashed_password_7');
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('Emma', 'Anderson', 'emma.anderson@example.com', 'hashed_password_8');
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('William', 'Thomas', 'william.thomas@example.com', 'hashed_password_9');
INSERT INTO public.users (first_name, last_name, email, password_hash) VALUES ('Olivia', 'Harris', 'olivia.harris@example.com', 'hashed_password_10');
INSERT INTO public.transactions (user_id, product_id, quantity, total_amount, status) VALUES (1, 1, 2, 399.98, 'completed');
INSERT INTO public.transactions (user_id, product_id, quantity, total_amount, status) VALUES (2, 3, 1, 149.99, 'pending');
INSERT INTO public.transactions (user_id, product_id, quantity, total_amount, status) VALUES (3, 5, 3, 388.50, 'completed');
INSERT INTO public.transactions (user_id, product_id, quantity, total_amount, status) VALUES (4, 7, 5, 149.75, 'failed');